Homework3
ivanseki/android-vjestina-tmdb pull request #3
Opened 2022-12-01 11:21 UTC by ivanseki

In every ViewModel I left initialState to empty, it works for home screen and favorites screen but when I click on movie to load MovieDetailsScreen the app crashes because of empty list (looks like it doesn't load data from movieRepository correctly). Couldn't figure out if it is related to mappers or flow of data or maybe something else.
Also, I can't figure out why it doesn't change favorite state when favorite button is clicked.

2022-12-05 11:38 UTC, ivan-varga requested changes

2022-12-05 11:38 UTC, ghost commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/MovieApp.kt
>          Log.d("MovieApp", "App started")
Remove all logs that were used for development/debugging. It's generally a good idea to remove these log messages since they don't bring any value to the codebase but introduce additional code which needs to be maintained.

2022-12-05 11:38 UTC, ghost commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                onClick = { onFavouriteButtonClick }
`onFavouriteButtonClick` is a function. You need to invoke it. That's why your favorites are not changing.
`onFavouriteButtonClick` -> `onFavouriteButtonClick()`

2022-12-05 11:38 UTC, ivan-varga commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favourites/FavoritesScreen.kt
> +        FavoritesRoute(
Routes should be used for navigation and state hoisting. 
Use pure composable functions for preview. In this case: FavoritesScreen.

2022-12-05 11:38 UTC, ivan-varga commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favourites/FavoritesScreen.kt
> +            onNavigateToMovieDetails = {return@FavoritesRoute} )
Formatting

2022-12-05 11:38 UTC, ivan-varga commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +        HomeRoute(
Same as for Favorites. Don't use Route for Preview

2022-12-05 11:38 UTC, ivan-varga commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        MovieDetailsRoute(
Same as for Favorites. Don't use Route for Preview

2022-12-06 15:28 UTC, ivanseki commented
Still can't figure out why the app crashes when MovieCard is clicked to open MovieDetailsScreen.

2022-12-06 15:30 UTC, ivanseki commented
Also when I look at FavoritesScreen on preview the cards are fine but when the app is running, the cards are vertically higher that they should be, any ideas on how to fix this?

2022-12-07 10:21 UTC, ghost commented
@ivanseki 

> Still can't figure out why the app crashes when MovieCard is clicked to open MovieDetailsScreen.  

When the card is clicked, the screen is open. The MovieDetailsViewModel emits an empty ViewState in the beginning (with empty lists for crew and cast). Since you use indexing in your composable you get `java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.`. You can fix this in various ways, I'll leave you to decide how you want to approach it :)

2022-12-07 10:39 UTC, ivan-varga commented
@ivanseki 
> Also when I look at FavoritesScreen on preview the cards are fine but when the app is running, the cards are vertically higher that they should be, any ideas on how to fix this?

The appearance of an item also depends on the parent container that the item is in. The preview is generated only for the card in isolation, while in the app there is a `LazyVerticalGrid` as a parent.
You are using `columns = GridCells.Fixed(3)` property for the LazyVerticalGrid which will try to reduce the width of the item to always fit the three items horizontally - this is why your items look elongated.
Secondly, in the preview you have defined a static width and height which are being rendered in Android Studio, while such constraints have not been put in the composable itself.
If you want your items to be shorter (or longer) you can define the height property for the card in the `FavoritesScreen` like this:
```kotlin
MovieCard(
                item = MovieCardViewState(
                    id = movie.id,
                    imageUrl = movie.imageUrl,
                    isFavorite = movie.isFavorite
                ),
                onClick = { onNavigateToMovieDetails(movie) },
                onFavouriteButtonClick = { onFavoriteButtonClick(movie.id) },
                modifier = Modifier.height(xxx.dp) <--- Your value here
            )
```

Also, during testing I found another issue which you should address - the LazyVerticalGrid in FavoritesScreen is set to wrap content (you can clearly see the items being cutoff when you (over)scroll). 
Here is how we can fix this.
The FavoriteScreen composable accepts a modifier, but never uses it. Please pass in the modifier parameter to the root composable (`LazyVerticalGrid`). When you do this, in your `FavoritesRoute` composable pass in a modifier which has `.fillMaxSize()` called to make the screen as big as possible. Like this:
```kotlin
FavoritesScreen(
        favoritesViewState = favoritesViewState,
        onNavigateToMovieDetails = onNavigateToMovieDetails,
        onFavoriteButtonClick = { movieId -> viewModel.toggleFavorite(movieId) },
       modifier = Modifier.fillMaxSize()
    )
```

2022-12-07 12:22 UTC, ivanseki commented
Fixed accessing index values in `MovieDetailsScreen` with `.getOrElse()` function (sending empty `CrewmanViewState` if index can't be accessed). Also made poster picture with full size because it just looks nicer :) 

Can I merge?

2022-12-07 14:29 UTC, ghost commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
>          )
@ivanseki 
It's not a good pratice to show "dummy data" (in this case `initialCrewmanViewState`) to the user since that can lead to a confusing UI if it renders on the screen. Also, it takes up resources from the mobile device.

A better solution would be to just not call composables if the data is not there but I'll accept this for now.
For the next PR try to not call the composable function if there is no data to show.
Also, the second crewman could be optional (nullable) since we might have 5 crew members to show (last column would just have 1 person to show).  Keep this in mind when rewriting this logic :)

2022-12-07 14:30 UTC, ivan-varga approved these changes
Overall a good PR, I like your proactivity! Keep it up 💪🏻 🚀

2022-12-08 10:09 UTC, merged